import { getElement } from "./dom.js";

export function createUiRefs() {
  const refs = {
    migrationStatus: getElement("migrationStatus"),
    screensList: getElement("screensList"),
    navButtons: document.querySelectorAll("[data-view]"),
    viewPanes: document.querySelectorAll("[data-view-pane]"),
    btnAddScreen: getElement("btnAddScreen"),
    btnSaveProject: getElement("btnSaveProject"),
    btnExportProject: getElement("btnExportProject"),
    btnImportProject: getElement("btnImportProject"),
    importProjectInput: getElement("importProjectInput"),
    btnOpenElectricalConfig: getElement("btnOpenElectricalConfig"),
    electricalConfigModal: getElement("electricalConfigModal"),
    btnCloseElectricalConfig: getElement("btnCloseElectricalConfig"),
    btnSaveElectricalConfig: getElement("btnSaveElectricalConfig"),
    cfgBrilho: getElement("cfgBrilho"),
    cfgMargem: getElement("cfgMargem"),
    cfgReservaCircuito: getElement("cfgReservaCircuito"),
    cfgPixelsPerPort: getElement("cfgPixelsPerPort"),
    cfgOverclock: getElement("cfgOverclock"),
    cfgSistema: getElement("cfgSistema"),
    cfgTensao: getElement("cfgTensao"),
    cfgSistemaHint: getElement("cfgSistemaHint"),
    btnImportCabinets: getElement("btnImportCabinets"),
    importCabinetInput: getElement("importCabinetInput"),
    btnAddCabinet: getElement("btnAddCabinet"),
    cabinetsList: getElement("cabinetsList"),
    cabinetTableBody: getElement("cabinetTableBody"),
    cabNome: getElement("cabNome"),
    cabLargura: getElement("cabLargura"),
    cabAltura: getElement("cabAltura"),
    cabPxW: getElement("cabPxW"),
    cabPxH: getElement("cabPxH"),
    cabPeso: getElement("cabPeso"),
    cabWatts: getElement("cabWatts"),
    cabFp: getElement("cabFp"),
    btnRebuildCanvas: getElement("btnRebuildCanvas"),
    cablingCanvas: getElement("cablingCanvas"),
    cablingSummary: getElement("cablingSummary"),
    cablingScreensList: getElement("cablingScreensList"),
    cfgCablingOrientation: getElement("cfgCablingOrientation"),
    cfgCablingStrategy: getElement("cfgCablingStrategy"),
    cablingQuickBar: getElement("cablingQuickBar"),
    testCardScreen: getElement("testCardScreen"),
    btnAddTestCardScreen: getElement("btnAddTestCardScreen"),
    btnClearTestCardScreens: getElement("btnClearTestCardScreens"),
    testCardSelectedScreens: getElement("testCardSelectedScreens"),
    testCardUseAllScreens: getElement("testCardUseAllScreens"),
    testCardLayout: getElement("testCardLayout"),
    testCardGapPx: getElement("testCardGapPx"),
    testCardGridCols: getElement("testCardGridCols"),
    testCardPreset: getElement("testCardPreset"),
    testCardTitle: getElement("testCardTitle"),
    testCardBg: getElement("testCardBg"),
    testCardFg: getElement("testCardFg"),
    testCardAccent: getElement("testCardAccent"),
    testCardShowGrid: getElement("testCardShowGrid"),
    testCardShowCabling: getElement("testCardShowCabling"),
    testCardShowNames: getElement("testCardShowNames"),
    testCardShowTargets: getElement("testCardShowTargets"),
    btnExportTestCardPng: getElement("btnExportTestCardPng"),
    btnExportTestCardPdf: getElement("btnExportTestCardPdf"),
    testCardCanvas: getElement("testCardCanvas"),
    testCardMeta: getElement("testCardMeta"),
    testCardPosX: getElement("testCardPosX"),
    testCardPosY: getElement("testCardPosY"),
    btnAutoAlignTestCard: getElement("btnAutoAlignTestCard"),
    btnTestCardZoomIn: getElement("btnTestCardZoomIn"),
    btnTestCardZoomOut: getElement("btnTestCardZoomOut"),
    btnTestCardZoomReset: getElement("btnTestCardZoomReset"),
    btnZoomIn: getElement("btnZoomIn"),
    btnZoomOut: getElement("btnZoomOut"),
    btnZoomReset: getElement("btnZoomReset"),
    btnPrintReport: getElement("btnPrintReport"),
    btnPrintCompact: getElement("btnPrintCompact"),
    reportType: getElement("reportType"),
    reportTypeDescription: getElement("reportTypeDescription"),
    btnExportDetailedReportPdf: getElement("btnExportDetailedReportPdf"),
    reportPreviewLead: getElement("reportPreviewLead"),
    reportPageCount: getElement("reportPageCount"),
    reportPreview: getElement("reportPreview"),
    reportBody: getElement("reportBody"),
    totArea: getElement("totArea"),
    totGab: getElement("totGab"),
    totPx: getElement("totPx"),
    totWatts: getElement("totWatts"),
    totKva: getElement("totKva"),
    rptGeneratedAt: getElement("rptGeneratedAt"),
    rptConfig: getElement("rptConfig"),
    rptProcessor: getElement("rptProcessor"),
    rptPorts: getElement("rptPorts"),
    rptCurrent: getElement("rptCurrent"),
    rptBreakerMin: getElement("rptBreakerMin"),
    rptBreaker: getElement("rptBreaker"),
    rptWeight: getElement("rptWeight"),
    dashTensao: getElement("dashTensao"),
    dashGab: getElement("dashGab"),
    dashPx: getElement("dashPx"),
    dashWatts: getElement("dashWatts"),
    dashKva: getElement("dashKva"),
    dashAmp: getElement("dashAmp"),
    dashBreaker: getElement("dashBreaker"),
  };

  refs.testCardPreview = null;
  refs.testCardDrag = null;
  refs.testCardPan = null;

  return refs;
}
